version: '3.8'

services:
  bot:
    build: .
    container_name: telegram_video_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./tmp:/tmp # Для временных файлов, если нужно